language: java
jdk: oraclejdk11
dist: trusty

addons:
  sonarcloud:
    organization: ddaninthe-github
    token:
      secure: a//7iR6cLjN3uqGVEubeQtq1004oQN1YYgNFIz+8N37o/ldoh/QfNE/gNgSfZ/WTTnEGoPAJpuCHLLBv8Bjfeg5Vx5Gg5+ORjyi6HpCZLnMSCkKca8Vm3Bu9uFYX2BjSfASPP16KIgTTnX9tezaK6oDUTII+bnQhoWF+3WKN1CynpFkGjuoLdfzgeYTqlbxsWe9p7GtWFTHuZSW/nzYu1eMTEYf18MiEpFIuOWB0K/edAa5ZfKZ53HIfhTA7rzacsr0EYg+7M34sgnAXfX8nRjGuRtCPZ+/iErmUROcJidtjM51OSK7OVfN9habUHgwhrnanENmxwMUcYNMGKFIaBEmg3pRwnWhL0HM/B0b7730quyHRiez4K3812qyn0oiRfIerplwlSlICs3bOKqPb7fMgLupOze6U4Yo/J/9xN/GSX2oWVxLliR5uP9wSuA2KCNTVCaaT97edRaQmrSABfJgeN5hNnnXnEvwAZUZd7WDlnEScHXDvaBP7OxXOOOQo4SoGi4vN0rIlRs6Bqvu8apKCG3VKLvJ8qauRnHb0gHEGbENrc84S23RoHgSxYV1bVyGbFhDJYvG3LcyMibZ84xAtRg3HTVnLdWtILEI3NEgZZNgv8836Pio6N1DBrWFvhpxXWECe03qHUVFdLangmH4p6tvpD/yjT0B3pWndkQM=

before_install:
- chmod a+x ./mvnw

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: s3
  access_key_id: AKIAIJ2ZDBIOBL75OJ6Q
  secret_access_key:
    secure: eMNY0/kSyH7TgHR46Ds9zrcdlTwZiNCjEi4OiOFcD558+8CVBF6FmSvRgOxD4n2mJk88hKhTozHvNS9AenGhGoP6DHPXSc3FLb5B5QUQk4MDl+WZuwVEZ0UlVZ+MEJBja4I5dswKkDlGEvfsDlJtcgssEbIrh50nH3txMqp4A7hYS89QfzvKQrYOunbrUzqSmTIGy+SQ5czjtHbuiHAxm7M0y1oALD5z8hKeLtpSX7hBAeEjBJfK+ZGOogYoEddFpQm+kXufbcGdjox83XrZ+NNVENGRkt0GKDKtnQnO84bbyIgZzKJ2l/1b7xSpbrEimUe28qh5ftwHipmxqFkClyDo41tI0vSxgLjYodcuB23cVhv+R3hEcfzQ43LgYnLSET/Si/TC1BQTIU/4jiPCLQFj8Bez6yzBTl3IqZLrDEzmf+yASCWiF6lZcEVZCdP3VcRGINBPwZ6RYpXkJ09H0yvxDS+TJVEgs+tPS6v5OjrBmmugXPJJmMtrGCmxIkSq8nxZsrK08Ylk0tDppdUELkVvhG3JKdfDaKvE1aNS/J4eIC3SX+oKTER819d6K3oJSpHnsi/9zReTaCH3zSv57lXKGv83wYz7jcSr2Eegwih5DNmEBHPI6i17oGbhZHVCnlNH74YvWrHJTz11kHqyY03VSecJnRAVVrCd4tdRFAs=
  bucket: S3 Bucket
  skip_cleanup: true
  on:
    branch: release
