language: java
jdk: oraclejdk11
dist: trusty

before_install:
- chmod a+x ./mvnw

deploy:
  provider: launchpad
  slug: "~esgi/botgether/+git/master"
  oauth_token:
    secure: 4Pv3fFXnQL6tIli9pPTtPztV2pjSjD2B7WdM/2cBX3tGNADlgqp+xDnB6FPWLk+kdQIL73Ir1KiWLJbWSjWGwfQbJkZpWHcUsacXPP+uNBoqeD37P4FDHZHt32IAG3ri8ohAfc9m3XF13sJGUDvk3YDXBJOjZxG8pyzOze+AWwRYxXSmPjxP0s3LtW90Yw6wMzvcmJzv7hu3TbGvuqLmXvs1JMyigD8dffhB4VPjgkFreKcOUXGvG0Rht3080TAaVOrGuqmxIhMRO66K4Qv1K06J4b/iXABPeYBDpcRBFr7TYQRmp4vdLjvUkQ4JIaf1QMmsdYzF4Tnl4Gfgye5vRjimct5xzS7XSQ3uTSL7aDRnAKhrJ45fH32sHUr1cBhiJftxhXgmNxf4XfuyLidUBb+XrhS9YPS+J81jL1E/iYuIEy62+nCfrhslRDESD90/GstQhGYK2n8JKiRtlEaARlESO38zFKX8KH0GeqKcV7ZQJuS/IVdQ20WCqXM+Xcjb/GxgxfJyxhYTnLd/S0KVxZei5n/Q/sIKBZoFCcv2QQkOhlUkVABzsWCHnSVT0o1+MjLIyenDxVfvUhumYPvt8C19Zr4KVgyB9Ggjkaxt/HLVQY3+7sZTzBXH6VgddyjtTwzPPZieOveIe2hmC7g937fjC2IegO5vSoD2SUVrqfI=
  oauth_token_secret:
    secure: xUTnGiiY4DL0j3ceFv1P7lYLireY0ximnsqTOmeBBH9x9SAHzZpAHQeyyY95Z15hWO1C9uJt5pnidE9iIWyIBBJBw0ev72fDeT4phQZjpcLte9nruIosEQcI6FHsKc/3e2PCDCbdBfpPGYlsvnvLabJpzd0hubtrZxvys3e92BwFpI5g5B5BqxEiRJGIC3wPjOXBwXiH+hIAtfIU+oxjNAsu0owRFpCfynuOjmXSTePLTrw/bpbKRkEsVscYx88hqgjLon5ZFmkxn77v/ffW9lIxReI3U4mZzjyvGsmyU0cLgMTlrkSyYXrgGPdEPXc1cemJQvvasbXgTt6DGZ5W2Fkdb7EYsj6leljGr3I/EGeOrmPd0kbcfWzcfEhHh9SCcQHLCtnrn6gpwaszqplDt6A3JrVS95I5wO5TfgN6ejy9K60mer+WU9tBd+beWWkbswx3UAA3ERDERxe6Hm5tc+lBM3DSXUXvHVH8fNJ2RaP0geoo6cvjs0cDO1mIAWUgIeuh/KIF5fczzFTM+xeueQ+hUk1hdV8miToqHCjw/goK59FzpZD1RpAselNQrry0ybaMiYcdo9BKk0b/OdW6ADgXXXxAaQLP7okxGdwCtkK3FUMLeFgKk5W3db2emNSVAK5s/Watc8SQlHsmW1VQjSncizlZCOe09kCZd/dMke0=
  on:
    branch: release