language: java
jdk: oraclejdk11
dist: trusty

addons:
  sonarcloud:
    organization: ddaninthe-github
    token:
      secure: a//7iR6cLjN3uqGVEubeQtq1004oQN1YYgNFIz+8N37o/ldoh/QfNE/gNgSfZ/WTTnEGoPAJpuCHLLBv8Bjfeg5Vx5Gg5+ORjyi6HpCZLnMSCkKca8Vm3Bu9uFYX2BjSfASPP16KIgTTnX9tezaK6oDUTII+bnQhoWF+3WKN1CynpFkGjuoLdfzgeYTqlbxsWe9p7GtWFTHuZSW/nzYu1eMTEYf18MiEpFIuOWB0K/edAa5ZfKZ53HIfhTA7rzacsr0EYg+7M34sgnAXfX8nRjGuRtCPZ+/iErmUROcJidtjM51OSK7OVfN9habUHgwhrnanENmxwMUcYNMGKFIaBEmg3pRwnWhL0HM/B0b7730quyHRiez4K3812qyn0oiRfIerplwlSlICs3bOKqPb7fMgLupOze6U4Yo/J/9xN/GSX2oWVxLliR5uP9wSuA2KCNTVCaaT97edRaQmrSABfJgeN5hNnnXnEvwAZUZd7WDlnEScHXDvaBP7OxXOOOQo4SoGi4vN0rIlRs6Bqvu8apKCG3VKLvJ8qauRnHb0gHEGbENrc84S23RoHgSxYV1bVyGbFhDJYvG3LcyMibZ84xAtRg3HTVnLdWtILEI3NEgZZNgv8836Pio6N1DBrWFvhpxXWECe03qHUVFdLangmH4p6tvpD/yjT0B3pWndkQM=

before_install:
- chmod a+x ./mvnw

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: launchpad
  slug: "~esgi/botgether/+git/master"
  oauth_token:
    secure: LoH2XwtGESdlBpBZA/YgwXNBLECh8b7BI/k46LmeQrE6eAfpyT/b4/1s6hFRI4cYUe8vjZa6BAI7RW89YXN+hmOi5k+gKh2ifktTxsuPnRKQNzu4fuAr2sMBXcnKPsxBIP8koHK8Xge1I8siEaHyqkaepkjKBQP/nw+iwcJjTtuuM0XF5a4Fl7lO2Z/ZLkRWO5d0jhA9qxKUcQpMbRwfciaJ5eLzzLyJAlhkFgzto6qIwWYB/ZDj66btVWlkXg81LGXMZLeUfswjB0iQea5Wb38Rdzyvqo0nL6EJ/tHoMqB2PmYjfy+ag3w0VJHNQsArVqJKVSTg66sUSRJGd8ukV4pJ5sRqUctU7kcCMBM3UBrWbK/GwTTMjblVsQLuZUAMvATxK+CgyS0bdBSTqhJpe5nNXvmf/BxYm7Mwu638WZCv3lFZJhNcNPBDgAhjBszuD1sOIEtvvOcMWOBfObtpIV4MkNx4Zkm2iEbxW8Y3mh4abbwzCnz6rwwcAznHVuNjPuMv6OQ7Hg0p36HwavStQgFAedQPgdNRR+hAWvSR2cCviv2o7syqedjxF/IMHZAuqwgeD8+u32pF4+vjErAYyMmCkFiViedZywa8zEpvcVeqkzw5JF/nQGXokc66gcGQJYIa7hHrlvgh16lk6wl3meNvMdA1Lo/2P6I6s3Hhctc=
  oauth_token_secret:
    secure: DgIW8VAMiSQtGlK21tnDJjeboTRezwZZPVSHEqxu3S4mllk0x7Pmf2AQOOh4+vTsll532AFJ6XklCCl4P9kcU/z4HqKtWC/fBEiVR+/1Rqm4Lj/c1LsjA4VUH7qRI0NaEW5I4A4ZSNqNRD4sEkkDX8KEUFvOxzyixkzJWR8ZrITJdH4/9IlFmbd4kiYEK9Itmp0gHMnrmxpckeLN4A+OeQDloKHpHD5F9wWdTUv61mSqejZJs8+UDxGbgiCuMtbsFsMja5ONZ4B8jWDFjy46r7gsJXY5pIaoHZnjFPXXkiP5SeEN+Tlosl+UBHO+IM/5SbbywNg6Alc8tom1fD2nA61ongjbZhtlN6hvzm3s1uyYhQ4mJKeXxyD/uDBjnnBkVZqTouwwD3P83feth+DRXXyBK5ScTJs6u3QBGUt8lGR9InvUloUKpTM/nkRTd3ZE8YzMuM2m/b4Rkk7bDPh19p2Ee60qXeq/mCqXc00D5wtzPWAsHfqpoPSEUS1zhOi4yDhV8XLyaqD85fG+cHCV61ip4jU1zc1APxyNjCL5W3Y6xYl9O+g4xkRynmXVzj5oCqUwRZRADLfIUkchzPX8TkkA4KKORG3ZEttdXidgLJYs9Fpl8Tot3yvxU/LTACPWGsqOXTqccSCcnggHIaDDbBbWUVeMoUBuOT+/8r+9LaU=
  on:
    branch: release
