language: java
jdk: oraclejdk11
dist: trusty

addons:
  sonarcloud:
    organization: ddaninthe-github
    token:
      secure: a//7iR6cLjN3uqGVEubeQtq1004oQN1YYgNFIz+8N37o/ldoh/QfNE/gNgSfZ/WTTnEGoPAJpuCHLLBv8Bjfeg5Vx5Gg5+ORjyi6HpCZLnMSCkKca8Vm3Bu9uFYX2BjSfASPP16KIgTTnX9tezaK6oDUTII+bnQhoWF+3WKN1CynpFkGjuoLdfzgeYTqlbxsWe9p7GtWFTHuZSW/nzYu1eMTEYf18MiEpFIuOWB0K/edAa5ZfKZ53HIfhTA7rzacsr0EYg+7M34sgnAXfX8nRjGuRtCPZ+/iErmUROcJidtjM51OSK7OVfN9habUHgwhrnanENmxwMUcYNMGKFIaBEmg3pRwnWhL0HM/B0b7730quyHRiez4K3812qyn0oiRfIerplwlSlICs3bOKqPb7fMgLupOze6U4Yo/J/9xN/GSX2oWVxLliR5uP9wSuA2KCNTVCaaT97edRaQmrSABfJgeN5hNnnXnEvwAZUZd7WDlnEScHXDvaBP7OxXOOOQo4SoGi4vN0rIlRs6Bqvu8apKCG3VKLvJ8qauRnHb0gHEGbENrc84S23RoHgSxYV1bVyGbFhDJYvG3LcyMibZ84xAtRg3HTVnLdWtILEI3NEgZZNgv8836Pio6N1DBrWFvhpxXWECe03qHUVFdLangmH4p6tvpD/yjT0B3pWndkQM=

before_install:
- chmod a+x ./mvnw

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: launchpad
  slug: "~esgi/botgether/+git/master"
  oauth_token:
    secure: O8B72Wz6TNTaBwFIAT09fh1WwrERcpUHE6DM340437laGl+jj8ZutaqnyowYmS+O1sBTpXGGbYxiZ/3n7Nzbw54pVcYRxAsjdXfyJ03pRjayQuOE4q6zrwe2zQ9uaYJx4MMQe7FzvU6C6fkMid+HzE511We1AYelhfQAxSSWAQho3BkplhxgeFmIKM0KmxO7pn7+DVJ28G8OS5tKVQmBqb+2PRZ//1KeF5txm7D1ti991CE1y/J1fgMvE+7OmUWae1q/uZ2lJZWjVTRsFx3n8/hSG5E8eaoEVYXewFIivhUv9LTN1zc8xfqw+ojcBsleR8kGSqPUI2NXnkShTWNO8w+U1dxHvpEL7n0hKp/umv2ukm6Ne5BjcvGKRllT4hI1PhlN3q5xuwwHR4MDp0AbXuRUoFjE/NeL+n35G5+nq59ANRS6WCbX6XcnbHgP4Y1KwYKFT+qsUU5WPNyDDT4eekh8zyaIBySxrH7rv+cIPYGPiILKnheI7A3R3/CHXlzCnEUVgwzeqnhgzLMSVQvG7B6yD5FGfUKK/uSEsmbcb7Qu2IZxtJ97EgEUSletcNGkqkkTlzBoQgy5Ch/4+RsyYKNUE5cLdP1k6TiSuQkJFEfbeO2CHooIc9QwnSJAqX8Wc6Auib8ZrgDjLPfFjZvaCM2lQHUZg1zLYdlH310VOQA=
  oauth_token_secret:
    secure: IBWe3VsFNJZ+yhQOXKMgOulVN7AsUMsmvp3uqaVnJzy7spSxfIiv8xIu7tH12Diz8QJ7Z8uZMhNFonn0kpHyKmJ9bt5mjsprsCN3kZzB4T98SecjYvTZRHtZcdo0ZFhg7JaF/epSPJ47SRh2rmERYDRlgnoWppkdU9kQaErAn3gOZQh1e5iDQJ8EEeE4ItkXI/nULupMzuaF/S93cscOBoWnx2o7V8YhCShtxCLzFiRpvijn1xAqambIxUuL54UTWTkTz/KZl1PsKkTmQiJXDiZdxz0XlcXJK4hR6WM/TVZPFdPNN1PiRftd4ioiLThK3ofTPWHOunroO0gzYttxL5CXQvED37ce12eSqHtu8icFRLkcxHpmgYQHcGAlV3RAtpkSrMtLx9sEBShr/ed0M1TKZ0iZ66gGQerVzqeyrwenfcuQypoUuGPLvGSIJj8fgnQS6vL2weDXZCJ2o8idYwtSA3hgm4Wkh08RsWuPAgwhzQU7u2U9RIOvbqagXSwfNhrs7lklSlLZ1M2lUHcXhQZ03JiL7DJR40jJqUVPTzwlE1ORzPGKA5cScusSIdyXcj0cOIEAIfCwmGaUlyKGVIQJo0pAobVO3ZHU7IPgBGTfx0LSo3gMbOVViv8NAWENDQugI5opCLYzDPq/tJ6l7704FLNyQZgp0W28jz5Th18=
  on:
    branch: release
