language: java
jdk: oraclejdk11
dist: trusty

addons:
  sonarcloud:
    organization: ddaninthe-github
    token:
      secure: a//7iR6cLjN3uqGVEubeQtq1004oQN1YYgNFIz+8N37o/ldoh/QfNE/gNgSfZ/WTTnEGoPAJpuCHLLBv8Bjfeg5Vx5Gg5+ORjyi6HpCZLnMSCkKca8Vm3Bu9uFYX2BjSfASPP16KIgTTnX9tezaK6oDUTII+bnQhoWF+3WKN1CynpFkGjuoLdfzgeYTqlbxsWe9p7GtWFTHuZSW/nzYu1eMTEYf18MiEpFIuOWB0K/edAa5ZfKZ53HIfhTA7rzacsr0EYg+7M34sgnAXfX8nRjGuRtCPZ+/iErmUROcJidtjM51OSK7OVfN9habUHgwhrnanENmxwMUcYNMGKFIaBEmg3pRwnWhL0HM/B0b7730quyHRiez4K3812qyn0oiRfIerplwlSlICs3bOKqPb7fMgLupOze6U4Yo/J/9xN/GSX2oWVxLliR5uP9wSuA2KCNTVCaaT97edRaQmrSABfJgeN5hNnnXnEvwAZUZd7WDlnEScHXDvaBP7OxXOOOQo4SoGi4vN0rIlRs6Bqvu8apKCG3VKLvJ8qauRnHb0gHEGbENrc84S23RoHgSxYV1bVyGbFhDJYvG3LcyMibZ84xAtRg3HTVnLdWtILEI3NEgZZNgv8836Pio6N1DBrWFvhpxXWECe03qHUVFdLangmH4p6tvpD/yjT0B3pWndkQM=

before_install:
- chmod a+x ./mvnw  
      
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - sonar-scanner

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar